apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ name }}-vnc-websockify-ingress"
  namespace: {{ namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: |
      toolmen-toolmen-auth@kubernetescrd,
      toolmen-universal-vnc-websockify-stripper@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - server.toolmen.bime.ntu.edu.tw
      secretName: server-frontend-tls-secret
  rules:
    - host: {{ host }}
      http:
        paths:
          - path: /{{ name }}/vnc
            pathType: Prefix
            backend:
              service:
                name: {{ name }}
                port:
                  number: 6080
          - path: /{{ name }}/websockify
            pathType: Prefix
            backend:
              service:
                name: {{ name }}
                port:
                  number: 6080
