FROM python:3.8

RUN pip install pipenv

ENV PROJECT_DIR=/usr/local/src/webapp

WORKDIR ${PROJECT_DIR}

COPY . ${PROJECT_DIR}/

# RUN pipenv install --system --deploy
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

CMD ["gunicorn", "-w", "16", "-b", "0.0.0.0:8080", "--access-logfile", "-", "app:app"]