apiVersion: v1
kind: Pod
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    labbox-pod-name: {{ name }}
spec:
  restartPolicy: Always
  {% if node %}
  nodeSelector:
    kubernetes.io/hostname: {{ node }}
  {% endif %}
  containers:
    - name: main
      image: {{ image }}
      ports:
        - containerPort: 8080
      env:
        - name: WORKSPACE_BASE_URL
          value: {{ name }}
        - name: AUTHENTICATE_VIA_JUPYTER
          value: {{ token }}
      volumeMounts:
        - name: nfs-nas-data
          mountPath: /workspace/NAS
        - name: nfs-nas-personal
          mountPath: /workspace
          subPath: {{ username }}
        - name: dshm
          mountPath: /dev/shm
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "40Gi"
  volumes:
  - name: nfs-nas-data
    persistentVolumeClaim:
      claimName: nfs-nas-data
  - name: nfs-nas-personal
    persistentVolumeClaim:
      claimName: nfs-nas-personal
  - name: dshm
    emptyDir:
      medium: Memory
