FROM python:3.11

RUN pip install pipenv
ENV PROJECT_DIR /usr/local/src/webapp
WORKDIR ${PROJECT_DIR}
COPY . ${PROJECT_DIR}/
RUN pipenv install --system --deploy


EXPOSE 3476

CMD ["gunicorn", "-w", "16", "-b", "0.0.0.0:3476", "--access-logfile", "-", "app:app"]
