FROM python:3.8

RUN pip install pipenv
ENV PROJECT_DIR /usr/local/src/webapp
WORKDIR ${PROJECT_DIR}
COPY . ${PROJECT_DIR}/
RUN pipenv install --system --deploy

EXPOSE 3476
ENTRYPOINT ["python", "app.py", "--host=0.0.0.0"]
